#!/usr/bin/env node

import inquirer from 'inquirer';
import fs from 'fs';
import chalk from 'chalk';
import { JiraClient } from './jira-client.js';

async function setupConfig() {
  console.log(chalk.blue.bold('🔧 JIRA Configuration Setup\n'));
  
  console.log(chalk.white('This will help you configure your JIRA connection.'));
  console.log(chalk.gray('You can also manually edit the .env file.\n'));

  const answers = await inquirer.prompt([
    {
      type: 'input',
      name: 'domain',
      message: 'JIRA Domain (e.g., yourcompany.atlassian.net):',
      validate: input => input.trim() ? true : 'Domain is required'
    },
    {
      type: 'input', 
      name: 'email',
      message: 'Your JIRA email address:',
      validate: input => {
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        return emailRegex.test(input) ? true : 'Please enter a valid email address';
      }
    },
    {
      type: 'password',
      name: 'apiToken',
      message: 'JIRA API Token (get from: https://id.atlassian.com/manage-profile/security/api-tokens):',
      validate: input => input.trim() ? true : 'API token is required'
    }
  ]);

  // Test connection before getting project info
  console.log(chalk.blue('\n🔌 Testing connection...'));
  
  try {
    const testClient = new JiraClient(answers.domain, answers.email, answers.apiToken);
    const connected = await testClient.testConnection();
    
    if (!connected) {
      console.error(chalk.red('❌ Connection failed. Please check your credentials.'));
      return;
    }

    // Get available projects
    console.log(chalk.blue('📋 Fetching available projects...'));
    const projects = await testClient.getProjects();
    
    const projectChoices = projects.map(project => ({
      name: `${project.key} - ${project.name}`,
      value: project.key
    }));

    const projectAnswer = await inquirer.prompt([
      {
        type: 'list',
        name: 'projectKey',
        message: 'Select your project:',
        choices: projectChoices
      }
    ]);

    // Optional filters
    const filterAnswers = await inquirer.prompt([
      {
        type: 'input',
        name: 'assignee',
        message: 'Filter by assignee (email address, leave empty for all):',
        default: ''
      },
      {
        type: 'input',
        name: 'statusFilter',
        message: 'Filter by status (e.g., "To Do", "In Progress", leave empty for open issues):',
        default: ''
      },
      {
        type: 'input',
        name: 'issueTypeFilter',
        message: 'Filter by issue type (e.g., "Bug", "Story", leave empty for all):',
        default: ''
      },
      {
        type: 'number',
        name: 'maxResults',
        message: 'Maximum number of issues to fetch:',
        default: 50,
        validate: input => input > 0 && input <= 1000 ? true : 'Please enter a number between 1 and 1000'
      }
    ]);

    // Create .env file content
    const envContent = `# JIRA Configuration
# Generated by setup script on ${new Date().toISOString()}

# Your JIRA domain (without https://)
JIRA_DOMAIN=${answers.domain}

# Your JIRA email address
JIRA_EMAIL=${answers.email}

# Your JIRA API token
JIRA_API_TOKEN=${answers.apiToken}

# Project key
PROJECT_KEY=${projectAnswer.projectKey}

# Optional: Specific assignee (leave empty for all)
ASSIGNEE=${filterAnswers.assignee}

# Optional: Issue status filter (leave empty for all)
STATUS_FILTER=${filterAnswers.statusFilter}

# Optional: Issue type filter (leave empty for all)
ISSUE_TYPE_FILTER=${filterAnswers.issueTypeFilter}

# Maximum number of issues to fetch
MAX_RESULTS=${filterAnswers.maxResults}
`;

    // Write .env file
    fs.writeFileSync('.env', envContent);
    
    console.log(chalk.green('\n✅ Configuration saved to .env file!'));
    console.log(chalk.blue('\n🚀 You can now run:'));
    console.log(chalk.white('   npm run fetch    - Fetch issues from JIRA'));
    console.log(chalk.white('   npm start        - Interactive mode'));
    
  } catch (error) {
    console.error(chalk.red('❌ Setup failed:'));
    console.error(chalk.red(error.message));
    
    if (error.response?.status === 401) {
      console.error(chalk.yellow('\n💡 Check your email and API token are correct.'));
    } else if (error.response?.status === 403) {
      console.error(chalk.yellow('\n💡 Make sure you have access to the JIRA instance.'));
    }
  }
}

setupConfig().catch(error => {
  console.error(chalk.red('Fatal error during setup:'), error);
  process.exit(1);
});